const sampleData = [
  { name: "BassBoost 5000", color: "Black", price: 79.99 },
  { name: "CrystalSound Pro", color: "Silver", price: 129.99 },
  { name: "ComfyTunes", color: "Blue", price: 59.99 },
  { name: "EliteNoise X3", color: "Black", price: 199.99 },
  { name: "ClearWave 2.0", color: "White", price: 89.99 },
  { name: "SonicBoom HD", color: "Red", price: 109.99 },
  { name: "StudioMax Wireless", color: "Gray", price: 159.99 },
  { name: "PureAudio Edge", color: "Green", price: 79.99 },
  { name: "DynamicBeats", color: "Black", price: 119.99 },
  { name: "GlowSound Neon", color: "Pink", price: 69.99 },
  { name: "StreamPro 360", color: "Blue", price: 99.99 },
  { name: "ComfortWave X", color: "White", price: 59.99 },
  { name: "BassFlow Ultra", color: "Black", price: 139.99 },
  { name: "HiFi Pulse 700", color: "Silver", price: 129.99 },
  { name: "WaveXpert Lite", color: "Gray", price: 49.99 },
  { name: "SoundSphere Z", color: "Black", price: 179.99 },
  { name: "VibeTrek Wireless", color: "Blue", price: 89.99 },
  { name: "ChillSound Pro", color: "White", price: 69.99 },
  { name: "ThunderBass Pro", color: "Black", price: 159.99 },
  { name: "EchoSounder X", color: "Red", price: 99.99 },
  { name: "UltraTune D700", color: "Silver", price: 149.99 },
  { name: "BeatBlaze XT", color: "Black", price: 119.99 },
  { name: "NeoBass Q5", color: "Gray", price: 79.99 },
  { name: "StreamLite Plus", color: "White", price: 69.99 },
  { name: "SoundShaper 2", color: "Blue", price: 89.99 },
  { name: "WaveBoost Pro", color: "Black", price: 109.99 },
  { name: "ClearTune Vibe", color: "Pink", price: 79.99 },
  { name: "ActiveBass HD", color: "Green", price: 139.99 },
  { name: "EchoBreeze Max", color: "Silver", price: 129.99 },
  { name: "SonixFlow Z", color: "Black", price: 99.99 },
  { name: "ChromaSound Plus", color: "Red", price: 89.99 },
  { name: "WaveConnect Prime", color: "White", price: 149.99 },
  { name: "VibeSphere XT", color: "Blue", price: 69.99 },
  { name: "BassTrek HD", color: "Black", price: 179.99 },
  { name: "GlowWave Neo", color: "Pink", price: 99.99 },
  { name: "MaxAudio Lite", color: "Silver", price: 49.99 },
  { name: "PulseTune X", color: "Gray", price: 119.99 },
  { name: "SoundPulse Pro", color: "Black", price: 159.99 },
  { name: "ClearWave Z5", color: "White", price: 89.99 },
  { name: "EliteBass Prime", color: "Blue", price: 139.99 },
];


export default sampleData;