const sampleData = [
  {
    name: "BassBoost 5000",
    color: "Black",
    price: 79.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "CrystalSound Pro",
    color: "Silver",
    price: 129.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "ComfyTunes",
    color: "Blue",
    price: 59.99,
    img: "/assets/asset3.jpg",
  },
  {
    name: "EliteNoise X3",
    color: "Black",
    price: 199.99,
    img: "/assets/asset4.jpg",
  },
  {
    name: "ClearWave 2.0",
    color: "White",
    price: 89.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "SonicBoom HD",
    color: "Red",
    price: 109.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "StudioMax Wireless",
    color: "Gray",
    price: 159.99,
    img: "/assets/asset6.jpg",
  },
  {
    name: "PureAudio Edge",
    color: "Green",
    price: 79.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "DynamicBeats",
    color: "Black",
    price: 119.99,
    img: "/assets/asset5.jpg",
  },
  {
    name: "GlowSound Neon",
    color: "Pink",
    price: 69.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "StreamPro 360",
    color: "Blue",
    price: 99.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "ComfortWave X",
    color: "White",
    price: 59.99,
    img: "/assets/asset3.jpg",
  },
  {
    name: "BassFlow Ultra",
    color: "Black",
    price: 139.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "HiFi Pulse 700",
    color: "Silver",
    price: 129.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "WaveXpert Lite",
    color: "Gray",
    price: 49.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "SoundSphere Z",
    color: "Black",
    price: 179.99,
    img: "/assets/asset4.jpg",
  },
  {
    name: "VibeTrek Wireless",
    color: "Blue",
    price: 89.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "ChillSound Pro",
    color: "White",
    price: 69.99,
    img: "/assets/asset5.jpg",
  },
  {
    name: "ThunderBass Pro",
    color: "Black",
    price: 159.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "EchoSounder X",
    color: "Red",
    price: 99.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "UltraTune D700",
    color: "Silver",
    price: 149.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "BeatBlaze XT",
    color: "Black",
    price: 119.99,
    img: "/assets/asset4.jpg",
  },
  {
    name: "NeoBass Q5",
    color: "Gray",
    price: 79.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "StreamLite Plus",
    color: "White",
    price: 69.99,
    img: "/assets/asset5.jpg",
  },
  {
    name: "SoundShaper 2",
    color: "Blue",
    price: 89.99,
    img: "/assets/asset3.jpg",
  },
  {
    name: "WaveBoost Pro",
    color: "Black",
    price: 109.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "ClearTune Vibe",
    color: "Pink",
    price: 79.99,
    img: "/assets/asset6.jpg",
  },
  {
    name: "ActiveBass HD",
    color: "Green",
    price: 139.99,
    img: "/assets/asset2.jpg",
  },
  {
    name: "EchoBreeze Max",
    color: "Silver",
    price: 129.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "SonixFlow Z",
    color: "Black",
    price: 99.99,
    img: "/assets/asset5.jpg",
  },
  {
    name: "ChromaSound Plus",
    color: "Red",
    price: 89.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "WaveConnect Prime",
    color: "White",
    price: 149.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "VibeSphere XT",
    color: "Blue",
    price: 69.99,
    img: "/assets/asset4.jpg",
  },
  {
    name: "BassTrek HD",
    color: "Black",
    price: 179.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "GlowWave Neo",
    color: "Pink",
    price: 99.99,
    img: "/assets/asset3.jpg",
  },
  {
    name: "MaxAudio Lite",
    color: "Silver",
    price: 49.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "PulseTune X",
    color: "Gray",
    price: 119.99,
    img: "/assets/asset6.jpg",
  },
  {
    name: "SoundPulse Pro",
    color: "Black",
    price: 159.99,
    img: "/assets/asset1.jpg",
  },
  {
    name: "ClearWave Z5",
    color: "White",
    price: 89.99,
    img: "/assets/asset4.jpg",
  },
  {
    name: "EliteBass Prime",
    color: "Blue",
    price: 139.99,
    img: "/assets/asset6.jpg",
  },
];

export default sampleData;
